site_name: methodaws
site_url: https://method-security.github.io/methodaws/
site_description: AWS enumeration capabilities for security teams of all sizes
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/Method-Security/methodaws
edit_uri: "blob/main/docs/"

nav:
  - Getting Started:
      - Overview: index.md
      - Installation: getting-started/installation.md
      - Basic Usage: getting-started/basic-usage.md
  - Docs:
      - Overview: docs/index.md
      - Capabilities:
        - Current Instance: docs/current_instance/index.md
        - EC2: docs/ec2/index.md
        - EKS: docs/eks/index.md
        - IAM: docs/iam/index.md
        - RDS: docs/rds/index.md
        - Route53: docs/route53/index.md
        - S3: docs/s3/index.md
        - Security Groups: docs/securitygroup/index.md
        - STS: docs/sts/index.md
        - VPC: docs/vpc/index.md
  - Contributing:
      - How to contribute: community/community.md
      - Development:
          - Setup: development/setup.md
          - Project Principles: development/principles.md
          - Adding New Capabilities: development/adding.md
theme:
  name: material
  language: "en"
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
    - content.action.edit
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - footnotes
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false
  version:
    method: mike
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/method_security
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/method-security
    - icon: fontawesome/brands/github
      link: https://github.com/Method-Security


plugins:
  - search
  - offline