name: 🔒 Ratchet Lint

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - develop

jobs:
  ratchet-check:
    name: Check for unpinned GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # ratchet:actions/checkout@v4
      - name: Install Ratchet
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release download --repo sethvargo/ratchet --pattern 'ratchet_linux_amd64.tar.gz' && tar -xzf ratchet_linux_amd64.tar.gz && chmod +x ratchet
      - name: Ratchet Check
        run: ./ratchet check .github/workflows/*.yml
