name: 🎉 Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    uses: ./.github/workflows/reusable-build.yml
    with:
      goreleaser_config: goreleaser.yml
      goreleaser_options: "--clean"
    secrets: inherit
    permissions:
      id-token: write # For cosign
      packages: write # For GHCR
      contents: read # Not required for public repositories, but for clarity
