name: 🎉 Release

on:
  workflow_call:

jobs:
  release:
    name: Release
    uses: ./.github/workflows/reusable-build.yml
    with:
      goreleaser_config: goreleaser.yml
      goreleaser_options: "--clean"
    secrets: inherit
    permissions:
      id-token: write # For cosign
      packages: write # For GHCR
      contents: write # To upload archives as release assets

  publish:
    name: Publish PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # ratchet:actions/setup-node@v6

      - name: Install Fern
        run: npm install -g fern-api

      - name: Generate Fern
        run: fern generate --group pypi --version ${{ github.ref_name }} --retry-rate-limited
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

    permissions:
      id-token: write # For cosign
      packages: write # For GHCR
      contents: write # To upload archives as release assets

  upload-to-s3:
    name: Upload to S3
    needs: [release]
    uses: ./.github/workflows/upload-to-s3.yml
    with:
      version: ${{ github.ref_name }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read
