name: 🎉 Release

on:
  push:
    tags:
      - "*" # Trigger on all tags

jobs:
  release:
    name: Release
    uses: ./.github/workflows/reusable-build.yml
    with:
      goreleaser_config: goreleaser.yml
      goreleaser_options: "--clean"
      chainguard_identity_name: CHAINCTL_IDENTITY_DEVELOP
    secrets: inherit
    permissions:
      id-token: write # For cosign
      packages: write # For GHCR
      contents: write # To upload archives as release assets
  publish-python:
    name: Publish Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install Fern
        run: npm install -g fern-api
      - name: Get Version
        run: echo "PROJECT_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Publish Fern to PyPi
        run: fern generate --group python --version $PROJECT_VERSION
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
