name: 🎉 Publish Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test_fern_publish:
    name: Test Fern Python Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # ratchet:actions/setup-node@v6

      - name: Install Fern CLI
        run: npm install -g fern-api

      - name: Generate Fern to Test PyPI
        run: fern generate --group pypi-test
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
