name: 🔨 Test Build

on:
  workflow_call:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 🔨 Reusable Go Build
    uses: ./.github/workflows/reusable-build.yml
    with:
      goreleaser_config: goreleaser.yml
      goreleaser_options: "--clean --snapshot"
    secrets: inherit
    permissions:
      id-token: write # For cosign
      packages: write # For GHCR
      contents: read # Not required for public repositories, but for clarity
