name: 🔨 Build Test
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Test Build
    uses: ./.github/workflows/reusable-build.yml
    with:
      goreleaser_config: goreleaser.yml
      goreleaser_options: "--clean --snapshot"
      chainguard_identity_name: CHAINCTL_IDENTITY_DEVELOP
    secrets: inherit
    permissions:
      id-token: write # For cosign
      packages: write # For GHCR
      contents: read # Not required for public repositories, but for clarity
