name: 🙏🏻 Verify

on:
  workflow_call:

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Fern Generated Code (Go)
        uses: actions/download-artifact@v4
        with:
          name: fern-generated-code
          path: generated/

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev

      - name: Godel Verify
        run: ./godelw verify
